### ISSUE TITLE
Add topic to the project to get listed under "velero-plugin"

### ISSUE THREAD

**Issue by jonasrosland** [portworx/ark-plugin#10]
Hi!

Just wanted to make sure you were aware of an easy way to get more attention to your Velero plugin, all you need to do is to add the `velero-plugin` topic and you'll get listed among the others over at https://github.com/search?q=topic%3Avelero-plugin&type=Repositories.

**Comment by wallnerryan** [comment]
Thanks @jonasrosland 👍

**Comment by disrani-px** [comment]
Added the topic

**Comment by jonasrosland** [comment]
Fantastic, thank you :)
We are currently building out a Plugins page on velero.io, would you be ok if we linked to your repo from it?
