### ISSUE TITLE
Heptio Ark is now Velero

### ISSUE THREAD

**Issue by rosskukulinski** [portworx/ark-plugin#6]
Hi! Thanks for creating a plugin for Ark.

I wanted to give you a heads up that today we announced the rename of the project: https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/.

The Velero team is working on a 0.11 release which will complete the code- and plugin-related changes to complete the rebranding. We'll update here when we've got more information on the plugin-author migration steps.

Let me know if you have any questions!

**Comment by disrani-px** [comment]
This has been updated
